//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorAutoProjectail.Appdata
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BorAutoBaseEntities : DbContext
    {
        public BorAutoBaseEntities()
            : base("name=BorAutoBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cars> cars { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<dillers> dillers { get; set; }
        public virtual DbSet<sells> sells { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
