//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorAutoProjectail.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class sells
    {
        public int id { get; set; }
        public int id_client { get; set; }
        public int id_diller { get; set; }
        public int id_car { get; set; }
        public System.DateTime date_sell { get; set; }
    
        public virtual cars cars { get; set; }
        public virtual clients clients { get; set; }
        public virtual dillers dillers { get; set; }
    }
}
